### ISSUE TITLE
Fix pwgweball.zip, pwgweb.zip download URLs

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#1]
Links 4 and 5 on http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/download.html do not work, please fix.
pwgweball.zip (1500MB!) Materials to construct an offline version of the web displays of the dictionary, including scanned images directory web/pdfpages
pwgweb.zip Materials to construct an offline version of the web displays of the dictionary. 
Note: Due to size constraints, the directory 'web/pdfpages' is not included. So, this offline version does not include access to the scanned images.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Time to respond to small suggestions from @gasyoun

**Comment by gasyoun** [comment]
One year anniversary.

**Comment by funderburkjim** [comment]
Both links now work . Happy Anniversary ! :sunglasses:

Regarding #4 (file names in PDFS):  If you open up the bookmarks in each pdf,  you should see first word on
page.  That's why  the files are named  pwg1_**bookmark**.pdf  ,etc.  

Regarding 3)  - Not enough server space for a zip of everything.

@gasyoun  Close the issue?

**Comment by gasyoun** [comment]
`Not enough server space for a zip of everything.` - how much is needed? We could host it as a .torrent somewhere else, the question would be how to update the files without hassle.

**Comment by gasyoun** [comment]
@funderburkjim torrent seems the way to give it a 2nd life, if the server will go down. Or if you will convert to Hindi. Everything will be lost.
