### ISSUE TITLE
Random Missing Abbreviations

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#33]
rāvaṇa [p= 6-0351] https://www.sanskrit-lexicon.uni-koeln.de/simple/pwg/ravana
 
`Hariv. 14518.  R. 1, 14, 37 (19 GORR.).`  where `GORR.` is an unmarked abbreviation.

`etzten Stellen liest die ed. Calc. fälschlich` where `ed. Calc.` Calcutta edition?

`oxyt. patron.`

`ältere Ausg.` not a real abbreviation, but means `older edition`.

`R. Gorr.` 1, 23, 19. 3, 36. 3. 6, 22, 7. 7, 16, 38.  `R. Gorr.` stands for Rāmāyaṇa, poema indiano di Valmici. Paris: Stamperia Reale. 1843–1870. (In octavo, comprising Ādikāṇḍa, Ayodhyākāṇḍa, Araṇyakāṇḍa, Kiṣkindhyākāṇḍa, Sundarakāṇḍa, Yuddhakāṇḍa, Uttarakāṇḍa.)
https://en.wikipedia.org/wiki/Gaspare_Gorresio

![ravana](https://user-images.githubusercontent.com/80761/83340075-a8fed800-a2dc-11ea-9980-d1e1f6f109c1.PNG)

**Comment by funderburkjim** [comment]
Have provided tool tips related to  Gorresio.  There are several variations.
* `R. GORR.` = `RĀMĀYAṆA, translation by Gaspare Gorresio. [Cologne Addition]`
   ![image](https://user-images.githubusercontent.com/6393033/83452800-64cc1e80-a427-11ea-85ca-6ec47cc79257.png)

* `GORRESIO` = `Gaspare Gorresio, translator of RĀMĀYAṆA [Cologne Addition]`
* `GORR.` = `GORRESIO`  
   * This is present in the [front matter](http://localhost/cologne/csl-doc/build/dictionaries/prefaces/pwgpref/pwgpref08.html)

Thank you for the references.

Similar additions for Gorresio abbreviations were made in PW; for example
https://www.sanskrit-lexicon.uni-koeln.de/simple/pw/ajAtasAra

**Comment by funderburkjim** [comment]
No changes were made pertaining to 
* `ed. Calc.`  occurs many times in complex contexts
* `oxyt. patron.`   
   * `oxyt.` occurs 429 times.  Probably abbreviation of 'oxytonon' 
   * `patron.` occurs 2092 times. Perhaps 'patron.'  is abbreviation for 
      *  English `patronymic`
      * German `Patronymikon`
   * `oxyt. patron.` occurs 10 times.   
* `Ausg.` occurs 1628 times;  You mention English as 'edition' .  Is German 'Ausgabe' ?

**Comment by gasyoun** [comment]
> You mention English as 'edition' . Is German 'Ausgabe' ?

Exactly.

**Comment by gasyoun** [comment]
> Probably abbreviation of 'oxytonon'

Right.

> 'patron.' is abbreviation for
Patronymikon, as it's a German book

**Comment by gasyoun** [comment]
`gadita n. das Reden, die Sprache H. ś. 81. ` so `ś.` same in book, but something fishy here, @fxru 

![dfsfsdfsdfsdfds](https://user-images.githubusercontent.com/80761/115069697-a0b38980-9efc-11eb-9866-2c28b0c53669.png)

**Comment by gasyoun** [comment]
@funderburkjim why in `Cit. beim Sch. zu Śāk. 31, 7.  Śrut. 44.  H. 15.` is `Sch.` not marked, but marked on same page higher?

![sch](https://user-images.githubusercontent.com/80761/115069845-d9ebf980-9efc-11eb-9d47-b26ae4fd9053.png)

**Comment by fxru** [comment]
Hey, sorry I seem to be missing the issue with `H. ç. 81`.  `H. ç.` is a defined reference in pwg. 

![Screenshot 2021-04-16 at 21 08 47](https://user-images.githubusercontent.com/1352294/115072822-26810600-9ef8-11eb-8019-2fa400fff69d.png)
[source](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/pwgpref/pwgpref08.html)

It seems to be an Addendum or something (well a शेष in any case) to `H.` 

![Screenshot 2021-04-16 at 21 16 46](https://user-images.githubusercontent.com/1352294/115073968-58df3300-9ef9-11eb-9670-dc62d710cc19.png)
[source](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/pwgpref/pwgpref08.html)

Sorry, if I’m missing the point here. Can you elaborate where the fishiness is, exactly?

**Comment by funderburkjim** [comment]
@fxru .  I think Marcis noticed that only the 'H' was in blue; when hovering over this, a tooltip was indicate 'HEMACANDRA'S ABHIDHĀNACINTĀMAṆI ...', whereas the tooltip should be
'Śeṣa's zu HEMACANDRA ...'.

The reason for this is that the tooltip was inaccurately identified, and the reason for the
inaccuracy is that the database had 'H. Ś.' instead of 'H. ś.'.

This has now been corrected (see [this commit](https://github.com/sanskrit-lexicon/csl-pywork/commit/2041339de2874aadd36854b57a8c272a7241abed)).

Note the minor difference compared to above: (`H. ś.` in blue)

![image](https://user-images.githubusercontent.com/6393033/115083257-160b6400-9ed5-11eb-9a30-7eca13e8c70e.png)

Details! Details!

**Comment by fxru** [comment]
Ok, that part I got. I was assuming there was something specifically addressed to me, as I was mentioned specifically. Details are crucial!

**Comment by funderburkjim** [comment]
@gasyoun  The reason that 'Sch.' is not in blue (and thus has no tooltip in the display) is
that it has no markup.  

The 'usual' markup in PWG is `<ls>Sch.</ls>` (occurs 5698 times).

There are 363 instances of ` Sch. `  (space on both sides). -- This is the case with the one under 'gad' that you pointed out.

However, there are also 569  cases like  ` Sch.</ls>` such as `<ls>P. 6, 3, 77, Sch.</ls>`.

and 130 cases where ' Sch.' occurs within a `<ls>.. Sch. ..</ls>`, but not at the end.

And there are still less common other varieties.

Since we don't want to have code like `<ls>.... <ls>Sch.</ls>...</ls>`,  it will take some
close observation to decide what changes are appropriate.

**Comment by gasyoun** [comment]
> Since we don't want to have code like <ls>.... <ls>Sch.</ls>...</ls>, it will take some
close observation to decide what changes are appropriate.

Still I guess most variants are enumerated now by you.

> I was assuming there was something specifically addressed to me

Not exactly, needed another pair of eyes, thanks ))

**Comment by funderburkjim** [comment]
The instance of 'Sch.' mentioned above is now marked:

![image](https://user-images.githubusercontent.com/6393033/115120696-cb452700-9f7c-11eb-910e-fea641984ede.png)

This was one of the changes mentioned in #35.

@gasyoun Close this issue ?

**Comment by gasyoun** [comment]
> The instance of 'Sch.' mentioned above is now marked

Thanks.
